# Generated by Django 5.1.13 on 2025-11-06 12:22

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="header_image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=tinymce.models.HTMLField(),
        ),
    ]
